spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviebookingapp?createDatabaseIfNotExist=true
    username: root
    password: root
    
  jpa:
     properties:
         hibernate:
           hbm2ddl:
               auto: update
           dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: movie-inventory-service
security:
  oauth2:
    resource:
        token-info-uri: http://localhost:8091/oauth/check_token
    client:
        client-id: client
        client-secret: password
#eureka:
#  client:
#       register-with-eureka: false
#   	fetch-registry: false
server: 
   port: 8081
